config/routes.rb
Rails.application.routes.draw do

  root to: 'globals#index'
  
   get '/index' => 'globals#index' , as: :index
   get '/about' => 'globals#about' , as: :about
   get '/contact' => 'globals#contact' , as: :contact
   get '/result' => 'globals#result_get' , as: :result_get
   post '/result' => 'globals#result' , as: :result
   post '/counties' => 'globals#counties' , as: :counties
   get '/no_result' => 'globals#no_result' , as: :no_result
   get '/import_file' => 'globals#import_file' , as: :import_file
   post '/import_file' => 'globals#upload_file' , as: :upload_file

end

app/models/datum.rb
class Datum < ActiveRecord::Base
	require 'csv'

	def self.import(file)
		Datum.all.delete_all
	    CSV.foreach(file.path, headers: true) do |row|
			row = Datum.create!({
				loan_number:row[0],
				product_description: row[1],
				type_product: row[2],
				census_tract: row[3],
				income_level: row[4],
				state: row[5],
				county: row[6],
				state_fips: row[7],
				county_fips: row[8],
				purpose: row[9],
				property_type: row[10],
				fico: row[11],
				application_date: Date.strptime(row[12], '%m/%d/%Y'),
			})
		end
	end

end

app/models/state_count.rb
class StateCount < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/globals_controller.rb
class GlobalsController < ApplicationController

	skip_before_action :verify_authenticity_token, only:[:counties]

	def index
		@state_counties = StateCount.all
	end

	def about
  	end

  	def contact
  	end

	def result
		min_fico = 300
		max_fico = 850
		min_fico = params[:min_fico].to_i if params[:min_fico].present? and params[:min_fico].to_i >= min_fico and params[:min_fico].to_i <= max_fico
		max_fico = params[:max_fico].to_i if params[:max_fico].present? and params[:max_fico].to_i >= min_fico and params[:max_fico].to_i <= max_fico
		@result = Datum.all
		@result = @result.where("lower(type_product) in (?)", params[:type_product].map(&:downcase)) if params[:type_product] and params[:type_product].count > 0
		@result = @result.where("lower(purpose) in (?)", params[:purpose].map(&:downcase)) if params[:purpose] and params[:purpose].count > 0
		@result = @result.where("lower(census_tract) in (?)", params[:census_tract].map(&:downcase)) if params[:census_tract] and params[:census_tract].count > 0
		@result = @result.where("lower(income_level) in (?)", params[:income_level].map(&:downcase)) if params[:income_level] and params[:income_level].count > 0
		@result = @result.where("lower(state) in (?)", params[:state].map(&:downcase)) if not params[:county] and params[:state] and params[:state].count > 0
		@result = @result.where("lower(county) in (?)", params[:county].map(&:downcase)) if params[:county] and params[:county].count > 0
		@result = @result.where("fico >= ? and fico <= ?", min_fico,  max_fico)
	end

	def result_get
		redirect_to index_path
	end

	def counties
		render json: StateCount.where(state: params[:states]).pluck(:county)				
	end

	def no_result
	end

	def import_file
	end

	def upload_file
		return redirect_to import_file_path, alert: "File is required." unless params[:file].present?
		Datum.import(params[:file])
		redirect_to import_file_path, notice: "File imported."
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/globals/about.html.erb
<h1>Welcome to the CRA Exchange</h1>
<p>We're building an exciting tool for you.  <a href="/contact">Contact Us</a> to keep in touch.</p>

app/views/globals/contact.html.erb
<h1>Email us at <a href="mailto:craexchange@gmail.com">craexchange@gmail.com</a></h1>

app/views/globals/import_file.html.erb
  <br>

	<h2>Import file</h2>
  <% if alert %>
  	<br>
  	<div class="alert alert-danger alert-dismissible" role="alert">
  		<strong>Error!: </strong> <%=alert%>
  	</div>
  	<br>
  <% end %>

  <% if notice %>
  	<br>
  	<div class="alert alert-success alert-dismissible" role="alert">
  		<strong>Succuss!: </strong> <%=notice%>
  	</div>
  <% end %>

<%= form_tag upload_file_path, multipart: true do %>
  <%= file_field_tag :file %>
  <br>
  <%= submit_tag "Import" %>
<% end %>

app/views/globals/index.html.erb
<div class="container">
	
		<br>
		<h2>Find CRAs to Purchase</h2>
		<h3>Please select the criteria you want to <b>Include</b> in your Query</h3>
		<br>

		<% if params["error"] %>
			<div class="alert alert-danger" role="alert">
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span class="sr-only">Error:</span>
				<% if params["error"].to_i == 1 %>
					Term is requerd
				<% elsif params["error"].to_i  == 2 %>
					Class is requerd
				<% elsif params["error"].to_i  == 3 %>
					type_product is requerd
				<% end %>
			</div>
			<br>
		<% end %>
		<div class="col-md-12">
			<div class="row">

				<%= form_tag(result_path, method: "post") do %>
					<div class="col-md-12">
						<b>Type: &nbsp;&nbsp;&nbsp;&nbsp;</b>
						
					  <label>
					    <input type="checkbox" name="type_product[]" id="optionsRadios1" value="Freddie" >
					    Freddie
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="type_product[]" id="optionsRadios2" value="Fannie">
					    Fannie
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="type_product[]" id="optionsRadios2" value="FHA">
					    FHA
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="type_product[]" id="optionsRadios2" value="VA">
					    VA
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="type_product[]" id="optionsRadios2" value="Rural">
					    Rural
					  </label>
					</div>

					<div class="col-md-12">
						<b>Purpose : &nbsp;&nbsp;&nbsp;&nbsp;</b>
						
					  <label>
					    <input type="checkbox" name="purpose[]" id="optionsRadios1" value="Purchase" >
					    Purchase
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="purpose[]" id="optionsRadios2" value="Refinance">
					    Refinance
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="purpose[]" id="optionsRadios2" value="Second home">
					    Second home
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="purpose[]" id="optionsRadios2" value="Investment">
					    Investment
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="purpose[]" id="optionsRadios2" value="Rural">
					    Rural
					  </label>
					</div>

					<div class="col-md-12">
						<b>Census Tract : &nbsp;&nbsp;&nbsp;&nbsp;</b>
						
					  <label>
					    <input type="checkbox" name="census_tract[]" id="optionsRadios1" value="low" >
					    low
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="census_tract[]" id="optionsRadios2" value="mid">
					    mid
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="census_tract[]" id="optionsRadios2" value="mod">
					    mod
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="census_tract[]" id="optionsRadios2" value="upper">
					    upper
					  </label>
						
					</div>

					<div class="col-md-12">
						<b>Income Level : &nbsp;&nbsp;&nbsp;&nbsp;</b>
						
					  <label>
					    <input type="checkbox" name="income_level[]" id="optionsRadios1" value="low" >
					    low
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="income_level[]" id="optionsRadios2" value="mid">
					    mid
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="income_level[]" id="optionsRadios2" value="mod">
					    mod
					  </label>
						&nbsp;
					  <label>
					    <input type="checkbox" name="income_level[]" id="optionsRadios2" value="upper">
					    upper
					  </label>
						
					</div>

					<div class="col-md-12" id="state-container">
						<br>
						<b>States  : </b>
						<select name="state[]" id="state" class="width-100p"   multiple="multiple">
							<% @state_counties.pluck(:state).uniq.each do |state| %>
								<option value="<%=state%>"><%=state%></option>
							<% end %> 
						</select>
					 
					</div>

					<div class="col-md-12" id="county-container">
						<br>
						<b>Counties   : </b>
						<select name="county[]" id="county" class="width-100p"  multiple="multiple">
							<% @state_counties.pluck(:county).uniq.each do |county| %>
								<option value="<%=county%>"><%=county%></option>
							<% end %>
						</select>
					 
					</div>


					<div class="col-md-12">
						<br>
						<b>min FICO score  : </b>
						<input type="number" name="min_fico" min="300" max="850" class="number-range">
					</div>

					<div class="col-md-12">
						<br>
						<b>max FICO score  :</b> 
						<input type="number" name="max_fico" min="300" max="850" class="number-range">
					</div>

					<div class="col-md-12">
						<br>
						<input type="submit" value="Search">
					</div>
				<% end %>
			</div>
		</div>

</div>

<script type="text/javascript">
	
	$( document ).ready(function() {
	    // array
		$("#state").on("change", function  () {
	    	var states = [];

			for (var i = $("#state-container .select2-selection__rendered .select2-selection__choice").length - 1; i >= 0; i--) {
				states.push($("#state-container .select2-selection__rendered .select2-selection__choice")[i].title);
			};

			console.log(states);

			data = {states: states};
			$.ajax({
			  url: "/counties",
			  type: "POST",
			  data: data
			}).done(function(response) {
				console.log(response);
				
				counties = [];
				countiesToAdd = [];
				
				for (var i = 0; i < $("#county-container .select2-selection__rendered .select2-selection__choice").length; i++) {
					counties.push($("#county-container .select2-selection__rendered .select2-selection__choice")[i].title);
				};

				console.log(counties);

				$("#county").html("");

				for (var i = 0; i < response.length; i++) {
					$("#county").append('<option value="'+response[i]+'">'+response[i]+'</option>');
				};

				var $selectStates = $("#county").select2();
				
				for (var i = 0; i < counties.length; i++) {
					if ($.inArray(counties[i], response)){
						countiesToAdd.push(counties[i]);
					}
				};
				$selectStates.val(countiesToAdd).trigger("change"); 

			});
		});

	});


	// <li class="select2-selection__choice" title="Yakutat, City and Borough of"><span class="select2-selection__choice__remove" role="presentation">×</span>Yakutat, City and Borough of</li>
</script>

app/views/globals/result.html.erb
<br>
<br>
<br>
	<h3 class="center-text">Your Results</h3>
<br>
	<h5 class="center-text">Number of results: <b><%=@result.count%></b>, Avarage FICO score: <b><%= @result.pluck(:fico).sum / @result.pluck(:fico).size.to_f%></b>,  Count of types: <b><%=@result.pluck(:type_product).uniq.size%></b></h4>
<br>


<table class="table table-bordered">
   <thead>
     <tr>

       <th>Loan Number</th>
       <th>Product Description</th>
       <th>Type</th>
       <th>Census Tract</th>
       <th>Income Level</th>
       <th>State</th>
       <th>County</th>
       <th>State FIPS</th>
       <th>County FIPS</th>
       <th>Purpose</th>
       <th>Property Type</th>
       <th>FICO</th>
       <th>Application Date</th>
								
     </tr>
   </thead>

   <tbody>
	   	<% 	
	   	@result.each do |result| %>
	      <tr>
	        <td><%=result.loan_number%></td>
	        <td><%=result.product_description%></td>
	        <td><%=result.type_product%></td>
	        <td><%=result.census_tract%></td>
	        <td><%=result.income_level%></td>
	        <td><%=result.state%></td>
	        <td><%=result.county%></td>
	        <td><%=result.state_fips%></td>
	        <td><%=result.county_fips%></td>
	        <td><%=result.purpose%></td>
	        <td><%=result.property_type%></td>
	        <td><%=result.fico%></td>
	        <td><%=result.application_date.strftime("%m/%d/%Y") %></td>
	      </tr>

     	<% end if @result%>
    </tbody>
</table>

app/views/layouts/_footer.html.erb
<p class="center-text">Copyright 2016</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CRA</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Search</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact Us</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Searcher</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/css/select2.min.css" rel="stylesheet" />
  <link href="/css/main.css" rel="stylesheet" />

  <%= csrf_meta_tags %>

  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2-rc.1/js/select2.min.js"></script>

</head>
<body>

<%= render 'layouts/navbar' %>
<div class="container">
	<%= yield %>
	<%= render 'layouts/footer' %>

</div>

<script type="text/javascript">
  $('select').select2();
</script>

</body>
</html>